"""add bill_versions, returns, return_lines, and user token revocation

Revision ID: 36cfc60b2f8e
Revises: 09a17b89d014
Create Date: 2026-08-16 23:20:05.768583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '36cfc60b2f8e'
down_revision: Union[str, None] = '09a17b89d014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_versions',
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('edited_by_email', sa.String(length=255), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_versions_bill_id'), 'bill_versions', ['bill_id'], unique=False)
    op.create_table('returns',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_returns_bill_id'), 'returns', ['bill_id'], unique=False)
    op.create_index(op.f('ix_returns_shop_id'), 'returns', ['shop_id'], unique=False)
    op.create_table('return_lines',
    sa.Column('return_id', sa.UUID(), nullable=False),
    sa.Column('bill_line_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['bill_line_id'], ['bill_lines.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_lines_return_id'), 'return_lines', ['return_id'], unique=False)
    op.add_column('users', sa.Column('tokens_valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tokens_valid_from')
    op.drop_index(op.f('ix_return_lines_return_id'), table_name='return_lines')
    op.drop_table('return_lines')
    op.drop_index(op.f('ix_returns_shop_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_bill_id'), table_name='returns')
    op.drop_table('returns')
    op.drop_index(op.f('ix_bill_versions_bill_id'), table_name='bill_versions')
    op.drop_table('bill_versions')
    # ### end Alembic commands ###
