"""replace tokens_valid_from with tokens_version

Revision ID: 536a4e7a39de
Revises: a68c7fc3eb1a
Create Date: 2026-08-17 12:01:30.185943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '536a4e7a39de'
down_revision: Union[str, None] = 'a68c7fc3eb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tokens_version', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('users', 'tokens_valid_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tokens_valid_from', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("date_trunc('second'::text, now())"), autoincrement=False, nullable=False))
    op.drop_column('users', 'tokens_version')
    # ### end Alembic commands ###
