"""add_supplier_prices_table

Revision ID: 5ff28802e9be
Revises: e0fad5231b7d
Create Date: 2026-08-21 13:44:57.415557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ff28802e9be'
down_revision: Union[str, None] = 'e0fad5231b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_prices',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'supplier_id', 'medicine_id', name='uq_supplier_prices_shop_sup_med')
    )
    op.create_index(op.f('ix_supplier_prices_medicine_id'), 'supplier_prices', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_supplier_prices_shop_id'), 'supplier_prices', ['shop_id'], unique=False)
    op.create_index(op.f('ix_supplier_prices_supplier_id'), 'supplier_prices', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_prices_supplier_id'), table_name='supplier_prices')
    op.drop_index(op.f('ix_supplier_prices_shop_id'), table_name='supplier_prices')
    op.drop_index(op.f('ix_supplier_prices_medicine_id'), table_name='supplier_prices')
    op.drop_table('supplier_prices')
    # ### end Alembic commands ###
