"""cascade delete leaf FKs referencing medicines and batches

Revision ID: 608694127a54
Revises: 536a4e7a39de
Create Date: 2026-08-17 14:13:22.745686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '608694127a54'
down_revision: Union[str, None] = '536a4e7a39de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('adjustments_batch_id_fkey', 'adjustments', type_='foreignkey')
    op.create_foreign_key(None, 'adjustments', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('bill_lines_batch_id_fkey', 'bill_lines', type_='foreignkey')
    op.drop_constraint('bill_lines_medicine_id_fkey', 'bill_lines', type_='foreignkey')
    op.create_foreign_key(None, 'bill_lines', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bill_lines', 'medicines', ['medicine_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('purchase_lines_medicine_id_fkey', 'purchase_lines', type_='foreignkey')
    op.drop_constraint('purchase_lines_batch_id_fkey', 'purchase_lines', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_lines', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'purchase_lines', 'medicines', ['medicine_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('purchases_supplier_id_fkey', 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('return_lines_batch_id_fkey', 'return_lines', type_='foreignkey')
    op.drop_constraint('return_lines_bill_line_id_fkey', 'return_lines', type_='foreignkey')
    op.create_foreign_key(None, 'return_lines', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'return_lines', 'bill_lines', ['bill_line_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('stock_ledger_batch_id_fkey', 'stock_ledger', type_='foreignkey')
    op.create_foreign_key(None, 'stock_ledger', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('supplier_return_lines_batch_id_fkey', 'supplier_return_lines', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_return_lines', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('supplier_returns_supplier_id_fkey', 'supplier_returns', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_returns', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_returns', type_='foreignkey')
    op.create_foreign_key('supplier_returns_supplier_id_fkey', 'supplier_returns', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'supplier_return_lines', type_='foreignkey')
    op.create_foreign_key('supplier_return_lines_batch_id_fkey', 'supplier_return_lines', 'batches', ['batch_id'], ['id'])
    op.drop_constraint(None, 'stock_ledger', type_='foreignkey')
    op.create_foreign_key('stock_ledger_batch_id_fkey', 'stock_ledger', 'batches', ['batch_id'], ['id'])
    op.drop_constraint(None, 'return_lines', type_='foreignkey')
    op.drop_constraint(None, 'return_lines', type_='foreignkey')
    op.create_foreign_key('return_lines_bill_line_id_fkey', 'return_lines', 'bill_lines', ['bill_line_id'], ['id'])
    op.create_foreign_key('return_lines_batch_id_fkey', 'return_lines', 'batches', ['batch_id'], ['id'])
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key('purchases_supplier_id_fkey', 'purchases', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'purchase_lines', type_='foreignkey')
    op.drop_constraint(None, 'purchase_lines', type_='foreignkey')
    op.create_foreign_key('purchase_lines_batch_id_fkey', 'purchase_lines', 'batches', ['batch_id'], ['id'])
    op.create_foreign_key('purchase_lines_medicine_id_fkey', 'purchase_lines', 'medicines', ['medicine_id'], ['id'])
    op.drop_constraint(None, 'bill_lines', type_='foreignkey')
    op.drop_constraint(None, 'bill_lines', type_='foreignkey')
    op.create_foreign_key('bill_lines_medicine_id_fkey', 'bill_lines', 'medicines', ['medicine_id'], ['id'])
    op.create_foreign_key('bill_lines_batch_id_fkey', 'bill_lines', 'batches', ['batch_id'], ['id'])
    op.drop_constraint(None, 'adjustments', type_='foreignkey')
    op.create_foreign_key('adjustments_batch_id_fkey', 'adjustments', 'batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###
