"""add doctor/rx/split-payment fields to bills, reorder_level to medicines

Revision ID: e0fad5231b7d
Revises: 608694127a54
Create Date: 2026-08-17 19:32:58.602646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0fad5231b7d'
down_revision: Union[str, None] = '608694127a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('doctor_id', sa.UUID(), nullable=True))
    op.add_column('bills', sa.Column('rx_no', sa.String(length=100), nullable=True))
    op.add_column('bills', sa.Column('diagnosis', sa.String(length=500), nullable=True))
    op.add_column('bills', sa.Column('payment_mode_2', sa.String(length=20), nullable=True))
    op.add_column('bills', sa.Column('amount_mode_1', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bills', sa.Column('amount_mode_2', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'bills', 'doctors', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.add_column('medicines', sa.Column('reorder_level', sa.Integer(), nullable=False, server_default='10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'reorder_level')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'amount_mode_2')
    op.drop_column('bills', 'amount_mode_1')
    op.drop_column('bills', 'payment_mode_2')
    op.drop_column('bills', 'diagnosis')
    op.drop_column('bills', 'rx_no')
    op.drop_column('bills', 'doctor_id')
    # ### end Alembic commands ###
